const { ControlPlaneStore, DEFAULT_PROJECTS } = require('./store');

function jsonParse(value, fallback) { try { return value ? JSON.parse(value) : fallback; } catch (_) { return fallback; } }
function jsonObject(value) { try { const parsed = JSON.parse(value); return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null; } catch (_) { return null; } }
function jsonArray(value) { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : null; } catch (_) { return null; } }

class D1ControlPlaneStore extends ControlPlaneStore {
  constructor(db, options = {}) {
    super(options); this.db = db;
    this.ready = this.hydrate();
  }
  async hydrate() {
    if (!this.db) return;
    const projects = await this.db.prepare('SELECT id,name,environment,runner_profile,capabilities_json FROM cp_projects').all();
    if (projects.results?.length) this.projects = new Map(projects.results.map((row) => [row.id, { id: row.id, key: row.id, name: row.name, environment: row.environment, runnerProfile: row.runner_profile, capabilities: jsonParse(row.capabilities_json, []) }]));
    else for (const project of DEFAULT_PROJECTS) await this.db.prepare('INSERT OR IGNORE INTO cp_projects (id,name,environment,runner_profile,capabilities_json,updated_at) VALUES (?,?,?,?,?,?)').bind(project.id, project.name, project.environment, project.runnerProfile, JSON.stringify(project.capabilities), new Date().toISOString()).run();
    const events = await this.db.prepare('SELECT event_id,schema_version,project,environment,severity,category,component,timestamp,message,context_json,source,correlation_id FROM cp_events ORDER BY timestamp DESC LIMIT 2000').all();
    for (const row of (events.results || []).reverse()) { const event = { schemaVersion: Number(row.schema_version || 1), eventId: row.event_id, project: row.project, environment: row.environment, severity: row.severity, category: row.category, component: row.component || row.source || '', timestamp: row.timestamp, message: row.message, context: jsonParse(row.context_json, {}), source: row.source, correlationId: row.correlation_id || null }; this.events.set(event.eventId, event); this.eventOrder.push(event.eventId); }
    const jobs = await this.db.prepare('SELECT * FROM cp_jobs ORDER BY created_at DESC LIMIT 500').all();
    for (const row of (jobs.results || [])) this.jobs.set(row.id, { id: row.id, projectId: row.project_id, type: row.type, risk: row.risk, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at, requestedBy: row.requested_by, payload: jsonParse(row.payload_json, {}), attemptCount: row.attempt_count, leaseOwner: row.lease_owner, leaseExpiresAt: row.lease_expires_at, result: jsonParse(row.result_json, null), error: row.error, idempotencyKey: row.idempotency_key });
    const runners = await this.db.prepare('SELECT * FROM cp_runners').all();
    for (const row of (runners.results || [])) this.runners.set(row.runner_id, { runnerId: row.runner_id, projectId: row.project_id, status: row.status, lastSeenAt: row.last_seen_at, version: row.version, hostLabel: row.host_label, capabilities: jsonParse(row.capabilities_json, []) });
    const alertRows = await this.db.prepare('SELECT * FROM cp_alerts').all();
    for (const row of (alertRows.results || [])) this.alerts.set(row.alert_key, { id: row.id, key: row.alert_key, project: row.project, category: row.category, environment: row.environment, message: row.message, eventId: row.event_id, createdAt: row.created_at, acknowledged: Boolean(row.acknowledged), status: row.acknowledged ? 'RECOVERED' : 'ACTIVE' });
    const configRows = await this.db.prepare('SELECT * FROM cp_operational_config ORDER BY updated_at DESC LIMIT 1').all();
    for (const row of (configRows.results || [])) { const config = jsonObject(row.config_json); if (config) this.operationalConfig = config; }
    const projectConfigRows = await this.db.prepare('SELECT * FROM cp_project_config').all();
    for (const row of (projectConfigRows.results || [])) { const config = jsonObject(row.project_json); if (config) this.projectConfigs.set(row.project_id, config); }
    const auditRows = await this.db.prepare('SELECT * FROM cp_config_audit ORDER BY changed_at ASC LIMIT 1000').all();
    for (const row of (auditRows.results || [])) { const names = jsonArray(row.setting_names_json); const context = jsonObject(row.context_json); if (names && context) this.configAudit.push({ auditId: row.audit_id, operationKey: row.operation_key, projectId: row.project_id, actor: row.actor, changedAt: row.changed_at, settingNames: names, context }); }
    const profileRows = await this.db.prepare('SELECT * FROM cp_desktop_profiles').all();
    for (const row of (profileRows.results || [])) { const profile = jsonObject(row.profile_json); if (profile) this.desktopProfiles.set(row.profile_id, profile); }
    const assetRows = await this.db.prepare('SELECT * FROM cp_excel_assets').all();
    for (const row of (assetRows.results || [])) { const asset = jsonObject(row.asset_json); if (asset) this.excelAssets.set(`${row.project_id}:${row.asset_id}`, asset); }
    const providerRows = await this.db.prepare('SELECT * FROM cp_provider_ops').all();
    for (const row of (providerRows.results || [])) { const provider = jsonObject(row.provider_json); if (provider) this.providerOperations.set(`${row.project_id}:${row.provider_id}`, provider); }
    const archiveRows = await this.db.prepare('SELECT * FROM cp_archives').all();
    for (const row of (archiveRows.results || [])) { const archive = jsonObject(row.archive_json); if (archive) { this.archives.set(row.archive_id, archive); if (row.operation_key) this.archiveOperations.set(row.operation_key, row.archive_id); } }
    const backupRows = await this.db.prepare('SELECT * FROM cp_backups').all();
    for (const row of (backupRows.results || [])) { const backup = jsonObject(row.backup_json); if (backup) { this.backups.set(row.backup_id, backup); if (row.operation_key) this.backupOperations.set(row.operation_key, row.backup_id); } }
    const retentionRows = await this.db.prepare('SELECT * FROM cp_retention_candidates').all();
    for (const row of (retentionRows.results || [])) { const candidate = jsonObject(row.candidate_json); if (candidate) this.retentionCandidates.set(row.candidate_id, candidate); }
    const reconciliationRows = await this.db.prepare('SELECT * FROM cp_reconciliation_results').all();
    for (const row of (reconciliationRows.results || [])) { const result = jsonObject(row.result_json); if (result) this.reconciliationResults.set(row.work_id, result); }
  }
  async ingestEvent(input) { const result = super.ingestEvent(input); if (result.ok && !result.duplicate) { await this.db.prepare('INSERT OR IGNORE INTO cp_events (event_id,schema_version,project,environment,severity,category,component,timestamp,message,context_json,source,correlation_id,received_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(result.event.eventId, result.event.schemaVersion, result.event.project, result.event.environment, result.event.severity, result.event.category, result.event.component, result.event.timestamp, result.event.message, JSON.stringify(result.event.context), result.event.source, result.event.correlationId, new Date().toISOString()).run(); for (const alert of this.alerts.values()) if (alert.project === result.event.project && alert.environment === result.event.environment) await this.db.prepare('INSERT OR REPLACE INTO cp_alerts (id,alert_key,project,category,environment,message,event_id,created_at,acknowledged) VALUES (?,?,?,?,?,?,?,?,?)').bind(alert.id, alert.key, alert.project, alert.category, alert.environment, alert.message, alert.eventId, alert.createdAt, alert.acknowledged ? 1 : 0).run(); } return result; }
  async createJob(input, requestedBy) { const result = super.createJob(input, requestedBy); if (result.ok && !result.duplicate) await this.persistJob(result.job); return result; }
  async persistJob(job) { await this.db.prepare('INSERT OR REPLACE INTO cp_jobs (id,project_id,type,risk,status,created_at,updated_at,requested_by,payload_json,attempt_count,lease_owner,lease_expires_at,result_json,error,idempotency_key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(job.id, job.projectId, job.type, job.risk, job.status, job.createdAt, job.updatedAt, job.requestedBy, JSON.stringify(job.payload || {}), job.attemptCount, job.leaseOwner, job.leaseExpiresAt, job.result == null ? null : JSON.stringify(job.result), job.error, job.idempotencyKey).run(); }
  async claimJob(runnerId, projectId, leaseMs) { const job = super.claimJob(runnerId, projectId, leaseMs); if (job) await this.persistJob(job); return job; }
  async resultJob(id, runnerId, result) { const output = super.resultJob(id, runnerId, result); if (output.ok && output.job) { await this.persistJob(output.job); const backupId = output.job.result?.backupRecordId; const backup = backupId && this.backups.get(backupId); if (backup) await this.db.prepare('INSERT OR REPLACE INTO cp_backups (backup_id,project_id,operation_key,backup_json,updated_at) VALUES (?,?,?,?,?)').bind(backup.backupId, backup.projectId, backup.operationKey || null, JSON.stringify(backup), backup.updatedAt).run(); const workId = output.job.result?.workId; const reconciliation = workId && this.reconciliationResults.get(workId); if (reconciliation) await this.db.prepare('INSERT OR REPLACE INTO cp_reconciliation_results (work_id,project_id,result_json,updated_at) VALUES (?,?,?,?)').bind(reconciliation.workId, reconciliation.projectId, JSON.stringify(reconciliation), reconciliation.updatedAt).run(); } return output; }
  async heartbeat(input) { const output = super.heartbeat(input); if (output.ok) { const runner = this.runners.get(output.runner.runnerId); await this.db.prepare('INSERT OR REPLACE INTO cp_runners (runner_id,project_id,status,last_seen_at,version,host_label,capabilities_json) VALUES (?,?,?,?,?,?,?)').bind(runner.runnerId, runner.projectId, runner.status, runner.lastSeenAt, runner.version, runner.hostLabel, JSON.stringify(runner.capabilities)).run(); } return output; }
  async acknowledgeAlert(id) { const alert = super.acknowledgeAlert(id); if (alert) await this.db.prepare('UPDATE cp_alerts SET acknowledged=1 WHERE id=?').bind(id).run(); return alert; }
  async saveOperationalConfig(input, actor, operationKey) { const result = super.saveOperationalConfig(input, actor, operationKey); if (result.ok && !result.duplicate) { await this.db.prepare('INSERT OR REPLACE INTO cp_operational_config (id,config_json,updated_at,updated_by,operation_key) VALUES (?,?,?,?,?)').bind('current', JSON.stringify(result.config), result.audit.changedAt, result.audit.actor, operationKey || null).run(); await this.db.prepare('INSERT OR IGNORE INTO cp_config_audit (audit_id,operation_key,project_id,actor,changed_at,setting_names_json,context_json) VALUES (?,?,?,?,?,?,?)').bind(result.audit.auditId, result.audit.operationKey, result.audit.projectId, result.audit.actor, result.audit.changedAt, JSON.stringify(result.audit.settingNames), JSON.stringify(result.audit.context)).run(); for (const project of result.config.projects || []) await this.db.prepare('INSERT OR REPLACE INTO cp_project_config (project_id,project_json,updated_at) VALUES (?,?,?)').bind(project.projectId, JSON.stringify(project), result.audit.changedAt).run(); if (result.event) await this.db.prepare('INSERT OR IGNORE INTO cp_events (event_id,schema_version,project,environment,severity,category,component,timestamp,message,context_json,source,correlation_id,received_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(result.event.eventId, result.event.schemaVersion, result.event.project, result.event.environment, result.event.severity, result.event.category, result.event.component || '', result.event.timestamp, result.event.message, JSON.stringify(result.event.context), result.event.source, result.event.correlationId, new Date().toISOString()).run(); } return result; }
  async upsertDesktopProfile(input, projectId) { const result = super.upsertDesktopProfile(input, projectId); if (result.ok) await this.db.prepare('INSERT OR REPLACE INTO cp_desktop_profiles (profile_id,project_id,profile_json,updated_at) VALUES (?,?,?,?)').bind(result.profile.id, result.profile.projectId, JSON.stringify(result.profile), result.profile.updatedAt).run(); return result; }
  async upsertExcelAsset(input) { const result = super.upsertExcelAsset(input); if (result.ok) await this.db.prepare('INSERT OR REPLACE INTO cp_excel_assets (asset_id,project_id,asset_json,updated_at) VALUES (?,?,?,?)').bind(result.asset.assetId, result.asset.project, JSON.stringify(result.asset), result.asset.updatedAt).run(); return result; }
  async upsertProviderOperation(input) { const result = super.upsertProviderOperation(input); if (result.ok) await this.db.prepare('INSERT OR REPLACE INTO cp_provider_ops (provider_id,project_id,provider_json,updated_at) VALUES (?,?,?,?)').bind(result.provider.providerId, result.provider.project, JSON.stringify(result.provider), result.provider.updatedAt).run(); return result; }
  async createArchive(input, operationKey) { const result = super.createArchive(input, operationKey); if (result.ok && !result.duplicate) await this.db.prepare('INSERT OR REPLACE INTO cp_archives (archive_id,project_id,operation_key,archive_json,updated_at) VALUES (?,?,?,?,?)').bind(result.archive.archiveId, result.archive.projectId, operationKey || null, JSON.stringify(result.archive), result.archive.updatedAt).run(); return result; }
  async updateArchiveRestore(archiveId, projectId, status, restoredAt) { const result = super.updateArchiveRestore(archiveId, projectId, status, restoredAt); if (result.ok) await this.db.prepare('UPDATE cp_archives SET archive_json=?,updated_at=? WHERE archive_id=? AND project_id=?').bind(JSON.stringify(result.archive), result.archive.updatedAt, result.archive.archiveId, result.archive.projectId).run(); return result; }
  async updateArchiveStatus(archiveId, projectId, status, providerReference) { const result = super.updateArchiveStatus(archiveId, projectId, status, providerReference); if (result.ok) await this.db.prepare('UPDATE cp_archives SET archive_json=?,updated_at=? WHERE archive_id=? AND project_id=?').bind(JSON.stringify(result.archive), result.archive.updatedAt, result.archive.archiveId, result.archive.projectId).run(); return result; }
  async createBackup(input, operationKey) { const result = super.createBackup(input, operationKey); if (result.ok && !result.duplicate) await this.db.prepare('INSERT OR REPLACE INTO cp_backups (backup_id,project_id,operation_key,backup_json,updated_at) VALUES (?,?,?,?,?)').bind(result.backup.backupId, result.backup.projectId, operationKey || null, JSON.stringify(result.backup), result.backup.updatedAt).run(); return result; }
  async saveRetentionCandidate(input) { const result = super.saveRetentionCandidate(input); if (result.ok) await this.db.prepare('INSERT OR REPLACE INTO cp_retention_candidates (candidate_id,project_id,candidate_json,updated_at) VALUES (?,?,?,?)').bind(result.candidate.candidateId, result.candidate.projectId, JSON.stringify(result.candidate), result.candidate.updatedAt).run(); return result; }
  async saveReconciliationResult(input) { const result = super.saveReconciliationResult(input); if (result.ok) await this.db.prepare('INSERT OR REPLACE INTO cp_reconciliation_results (work_id,project_id,result_json,updated_at) VALUES (?,?,?,?)').bind(result.result.workId, result.result.projectId, JSON.stringify(result.result), result.result.updatedAt).run(); return result; }
  async recordDailySystemEvidence(input) { const result = super.recordDailySystemEvidence(input); if (result.ok && result.event && !result.duplicate) { await this.db.prepare('INSERT OR IGNORE INTO cp_events (event_id,schema_version,project,environment,severity,category,component,timestamp,message,context_json,source,correlation_id,received_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(result.event.eventId, result.event.schemaVersion, result.event.project, result.event.environment, result.event.severity, result.event.category, result.event.component || '', result.event.timestamp, result.event.message, JSON.stringify(result.event.context), result.event.source, result.event.correlationId, new Date().toISOString()).run(); for (const alert of this.alerts.values()) if (alert.project === result.event.project && alert.environment === result.event.environment) await this.db.prepare('INSERT OR REPLACE INTO cp_alerts (id,alert_key,project,category,environment,message,event_id,created_at,acknowledged) VALUES (?,?,?,?,?,?,?,?,?)').bind(alert.id, alert.key, alert.project, alert.category, alert.environment, alert.message, alert.eventId, alert.createdAt, alert.acknowledged ? 1 : 0).run(); } if (result.reconciliation) await this.db.prepare('INSERT OR REPLACE INTO cp_reconciliation_results (work_id,project_id,result_json,updated_at) VALUES (?,?,?,?)').bind(result.reconciliation.workId, result.reconciliation.projectId, JSON.stringify(result.reconciliation), result.reconciliation.updatedAt).run(); return result; }
}

module.exports = { D1ControlPlaneStore };
