const { normalizeProjectKey } = require('./controlPlane/contracts');
const { hash } = require('./archive');

const VERIFICATION_STATUSES = Object.freeze(['PENDING', 'VERIFIED', 'MISMATCH', 'ERROR']);
const RETENTION_CLASSES = Object.freeze(['CURRENT_TODAY', 'HISTORICAL_SEVEN_DAY', 'UNRESOLVED_EVIDENCE']);
function text(value, max = 500) { return String(value == null ? '' : value).trim().slice(0, max); }
function iso(value) { const d = new Date(value == null ? Date.now() : value); return Number.isNaN(d.getTime()) ? null : d.toISOString(); }
function validateBackupRecord(input = {}) { const projectId = normalizeProjectKey(input.projectId || input.project); const assetId = text(input.assetId, 160); const createdAt = iso(input.createdAt); const sourceHash = text(input.sourceHash, 128); const backupHash = text(input.backupHash, 128); if (!projectId) return { ok: false, error: 'backup projectId is invalid or missing' }; if (!assetId) return { ok: false, error: 'backup assetId is required' }; if (!createdAt || !sourceHash || !backupHash) return { ok: false, error: 'backup timestamp and hashes are required' }; const verificationStatus = text(input.verificationStatus || 'PENDING', 30).toUpperCase(); if (!VERIFICATION_STATUSES.includes(verificationStatus)) return { ok: false, error: 'backup verificationStatus is unsupported' }; const retentionClass = text(input.retentionClass || 'CURRENT_TODAY', 40).toUpperCase(); if (!RETENTION_CLASSES.includes(retentionClass)) return { ok: false, error: 'backup retentionClass is unsupported' }; return { ok: true, value: { backupId: text(input.backupId, 160) || `bkp_${Date.now()}_${Math.random().toString(36).slice(2)}`, projectId, assetId, sourceHash: hash(sourceHash), backupHash: hash(backupHash), createdAt, period: text(input.period || input.businessDate, 80) || null, localBackupReference: text(input.localBackupReference, 500) || null, archiveReference: text(input.archiveReference, 160) || null, verificationStatus, retentionClass, unresolvedEvidence: retentionClass === 'UNRESOLVED_EVIDENCE' || verificationStatus === 'MISMATCH' || verificationStatus === 'ERROR' } }; }
function retentionCandidate(record, now = new Date()) { const age = new Date(now).getTime() - Date.parse(record.createdAt); return { candidate: record.retentionClass === 'HISTORICAL_SEVEN_DAY' && age >= 7 * 24 * 60 * 60 * 1000 && !record.unresolvedEvidence, destructiveAction: false, reason: record.unresolvedEvidence ? 'unresolved_evidence_must_be_retained' : 'retention_candidate_only' }; }
module.exports = { VERIFICATION_STATUSES, RETENTION_CLASSES, validateBackupRecord, retentionCandidate };
